project:
  type: website
  output-dir: docs
  resources:
    - google56073bacba8f92a9.html

website:
  title: "Serena DeStefani"
  description: "Serena DeStefani -- Postdoctoral researcher in cognitive psychology at The Ohio State University. Research on social cognition, gaze detection, face processing, and autism."
  site-url: "https://seredes.github.io"
  favicon: favicon.png

  open-graph:
    locale: en_US
    site-name: "Serena DeStefani"
  twitter-card:
    card-style: summary
  navbar:
    title: false
    pinned: true
    search: false
    collapse: false
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: about.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Resources
        href: resources.qmd

  page-footer:
    left: "© 2026 Serena DeStefani"
    right: "Made with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      light: styles.scss
      dark: [styles.scss, styles-dark.scss]
    grid:
      body-width: 900px
    toc: true
    toc-location: left
    toc-title: ""
    include-in-header:
      - fontawesome.html
      - schema.html

editor: visual
